name: dynamic_url_image_cache
description: A image provider that caches the image with an ID, useful for images with dynamic urls, like S3 images.
version: 0.0.4
homepage: https://github.com/Gabanelli
repository: https://github.com/Gabanelli/dynamic_url_image_cache

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
